#This is the implementation of country code according to 3166-1 standards
#See #https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv
#for a complete list

class country_code:
	def __init__(self,i_fallback):
		self.fallback=i_fallback
		self.iso_3166_dict = {
			"Afghanistan": "af",
			"Albania": "al",
			"Algeria": "dz",
			"Andorra": "ad",
			"Angola": "ao",
			"Antigua e Barbuda": "ag",
			"Argentina": "ar",
			"Armenia": "am",
			"Australia": "au",
			"Austria": "at",
			"Azerbaigian": "az",
			"Bahamas": "bs",
			"Bahrain": "bh",
			"Bangladesh": "bd",
			"Barbados": "bb",
			"Belgio": "be",
			"Belize": "bz",
			"Benin": "bj",
			"Bhutan": "bt",
			"Bolivia": "bo",
			"Bosnia ed Erzegovina": "ba",
			"Botswana": "bw",
			"Brasile": "br",
			"Brunei": "bn",
			"Bulgaria": "bg",
			"Burkina Faso": "bf",
			"Burundi": "bi",
			"Cambogia": "kh",
			"Camerun": "cm",
			"Canada": "ca",
			"Capo Verde": "cv",
			"Repubblica Centrafricana": "cf",
			"Ciad": "td",
			"Cile": "cl",
			"Cina": "cn",
			"Colombia": "co",
			"Comore": "km",
			"Congo (Rep. del)": "cg",
			"Congo (Dem. Rep. del)": "cd",
			"Corea del Nord": "kp",
			"Corea del Sud": "kr",
			"Costa d'Avorio": "ci",
			"Costa Rica": "cr",
			"Croazia": "hr",
			"Cuba": "cu",
			"Curaçao": "cw",
			"Cipro": "cy",
			"Cechia": "cz",
			"Danimarca": "dk",
			"Dominica": "dm",
			"Ecuador": "ec",
			"Egitto": "eg",
			"El Salvador": "sv",
			"Equador Guinea": "gq",
			"Eritrea": "er",
			"Estonia": "ee",
			"Eswatini": "sz",
			"Etiopia": "et",
			"Figi": "fj",
			"Filippine": "ph",
			"Finlandia": "fi",
			"Francia": "fr",
			"Gabon": "ga",
			"Gambia": "gm",
			"Georgia": "ge",
			"Ghana": "gh",
			"Giamaica": "jm",
			"Giappone": "jp",
			"Gibilterra": "gi",
			"Grecia": "gr",
			"Grenada": "gd",
			"Guadalupa": "gp",
			"Guam": "gu",
			"Guatemala": "gt",
			"Guinea": "gn",
			"Guinea-Bissau": "gw",
			"Guinea equatoriale": "gq",
			"Guyana": "gy",
			"Haiti": "ht",
			"Honduras": "hn",
			"Hong Kong": "hk",
			"India": "in",
			"Indonesia": "id",
			"Irlanda": "ie",
			"Islanda": "is",
			"Israele": "il",
			"Italia": "it",
			"Jamaica": "jm",
			"Giappone": "jp",
			"Giordania": "jo",
			"Kazakhstan": "kz",
			"Kenia": "ke",
			"Kiribati": "ki",
			"Korea del Sud": "kr",
			"Kuwait": "kw",
			"Laos": "la",
			"Lesotho": "ls",
			"Lettonia": "lv",
			"Libano": "lb",
			"Liberia": "lr",
			"Libia": "ly",
			"Liechtenstein": "li",
			"Lituania": "lt",
			"Lussemburgo": "lu",
			"Macau": "mo",
			"Madagascar": "mg",
			"Malawi": "mw",
			"Malesia": "my",
			"Mali": "ml",
			"Malta": "mt",
			"Marocco": "ma",
			"Mauritius": "mu",
			"Mauritania": "mr",
			"Messico": "mx",
			"Micronesia": "fm",
			"Moldavia": "md",
			"Monaco": "mc",
			"Mongolia": "mn",
			"Mozambico": "mz",
			"Namibia": "na",
			"Nauru": "nr",
			"Nepal": "np",
			"Nicaragua": "ni",
			"Niger": "ne",
			"Nigeria": "ng",
			"Niue": "nu",
			"Norvegia": "no",
			"Nuova Zelanda": "nz",
			"Oman": "om",
			"Paesi Bassi": "nl",
			"Pakistan": "pk",
			"Palau": "pw",
			"Panama": "pa",
			"Papua Nuova Guinea": "pg",
			"Paraguay": "py",
			"Perù": "pe",
			"Polonia": "pl",
			"Portogallo": "pt",
			"Puerto Rico": "pr",
			"Ruanda": "rw",
			"Romania": "ro",
			"Russia": "ru",
			"Saint Kitts e Nevis": "kn",
			"Saint Lucia": "lc",
			"Saint Vincent e Grenadine": "vc",
			"Samoa": "ws",
			"San Marino": "sm",
			"Sao Tome e Principe": "st",
			"Senegal": "sn",
			"Serbia": "rs",
			"Seychelles": "sc",
			"Sierra Leone": "sl",
			"Singapore": "sg",
			"Siria": "sy",
			"Somalia": "so",
			"Sri Lanka": "lk",
			"Stati Uniti": "us",
			"Sud Africa": "za",
			"Sudan": "sd",
			"Suriname": "sr",
			"Svezia": "se",
			"Svizzera": "ch",
			"Tagikistan": "tj",
			"Taiwan": "tw",
			"Tanzania": "tz",
			"Tailandia": "th",
			"Togo": "tg",
			"Tonga": "to",
			"Trinidad e Tobago": "tt",
			"Tunisia": "tn",
			"Turchia": "tr",
			"Tuvalu": "tv",
			"Uganda": "ug",
			"Ucraina": "ua",
			"Uruguay": "uy",
			"Uzbekistan": "uz",
			"Vanuatu": "vu",
			"Vaticano": "va",
			"Venezuela": "ve",
			"Viet Nam": "vn",
			"Zambia": "zm",
			"Zimbabwe": "zw"
		}
				
	def get_country_code(self,value):
		if str(value) in self.iso_3166_dict:
			return self.iso_3166_dict[value]
		else:
			return self.iso_3166_dict[self.fallback]